In [14]:
import pandas as pd;
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


# Hoody

In [15]:
hoody = pd.read_csv("./hoodedjacket_e.csv")

In [16]:
hoody.head()

Unnamed: 0  Sex  Reviewer_Sex Reviewer_Bought_Size  Height  Weight  Upper  \
0           0    0             0                    M     170      60   67.0   
1           1    0             0                    M     170      66   67.0   
2           2    0             0                    M     165      64   67.0   
3           3    0             0                    M     182      85   67.0   
4           4    0             0                    M     175      72   67.0   

   Shoulder  Chest   Arm  Review  
0      48.5   54.5  63.0       1  
1      48.5   54.5  63.0       1  
2      48.5   54.5  63.0       1  
3      48.5   54.5  63.0       1  
4      48.5   54.5  63.0       2

In [17]:
x = hoody.drop(['Reviewer_Bought_Size','Unnamed: 0', 'Review'], axis=1)
y = hoody.iloc[:,-1]

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [19]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train , Y_train)
params = {
    'n_estimators':[100],
    'max_depth' : [6, 8, 10, 12], 
    'min_samples_leaf' : [8, 12, 18 ],
    'min_samples_split' : [8, 16, 20]
}
rf_clf = RandomForestClassifier(random_state=0, n_jobs=-1)
grid_cv = GridSearchCV(rf_clf , param_grid=params , cv=2, n_jobs=-1 )
grid_cv.fit(X_train , Y_train)
rf_clf1 = RandomForestClassifier(n_estimators=300, max_depth=10, min_samples_leaf=8, \
                                 min_samples_split=8, random_state=0)
rf_clf1.fit(X_train , Y_train)
pred = rf_clf1.predict(X_test)
print(pred)
print(f'예측 정확도: {accuracy_score(Y_test , pred):.4f}')

[1 1 1 ... 1 1 1]
예측 정확도: 0.8702


In [20]:
import joblib
joblib.dump(rf_clf1,'./hoody_model.pkl', compress=9)

['./hoody_model.pkl']

# Jean 

In [22]:
jean = pd.read_csv("./jeans_e.csv", encoding="CP949")

In [23]:
jean.head()

Unnamed: 0  Sex  Reviewer_Sex Reviewer_Bought_Size  Height  Weight  Leg  \
0           0    0             0                    L     169      63  106   
1           1    0             0                    L     174      64  106   
2           2    0             0                    L     175      78  106   
3           3    0             0                    L     180      75  106   
4           4    0             0                    L     178      73  106   

   Waist  Thigh  Bot_Len  Bot_Area  Review  
0   41.0   33.0     29.0      23.0       1  
1   41.0   33.0     29.0      23.0       2  
2   41.0   33.0     29.0      23.0       2  
3   41.0   33.0     29.0      23.0       1  
4   41.0   33.0     29.0      23.0       2

In [25]:
x = jean.drop(['Unnamed: 0', 'Reviewer_Bought_Size','Review'], axis=1)
y = jean.iloc[:,-1]

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [27]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train , Y_train)
params = {
    'n_estimators':[100],
    'max_depth' : [6, 8, 10, 12], 
    'min_samples_leaf' : [8, 12, 18 ],
    'min_samples_split' : [8, 16, 20]
}
rf_clf = RandomForestClassifier(random_state=0, n_jobs=-1)
grid_cv = GridSearchCV(rf_clf , param_grid=params , cv=2, n_jobs=-1 )
grid_cv.fit(X_train , Y_train)
rf_clf1 = RandomForestClassifier(n_estimators=300, max_depth=10, min_samples_leaf=8, \
                                 min_samples_split=8, random_state=0)
rf_clf1.fit(X_train , Y_train)
pred = rf_clf1.predict(X_test)
print(pred)
print(f'예측 정확도: {accuracy_score(Y_test , pred):.4f}')

[1 1 1 ... 1 1 1]
예측 정확도: 0.8361


In [28]:
joblib.dump(rf_clf1,'./jean_model.pkl', compress=9)

['./jean_model.pkl']

# Coat

In [29]:
coat = pd.read_csv('./coat_e.csv', encoding="CP949")

In [30]:
coat.head()

Unnamed: 0  Sex  Reviewer_Sex Reviewer_Bought_Size  Height  Weight  Upper  \
0           0    0             1                    L     162      57  108.0   
1           1    0             0                    L     171      53  108.0   
2           2    0             0                    L     180      72  108.0   
3           3    0             0                    L     182      73  108.0   
4           4    0             0                    L     175      65  108.0   

   Shoulder  Chest   Arm  Review  
0      60.5   69.5  64.0       2  
1      60.5   69.5  64.0       1  
2      60.5   69.5  64.0       1  
3      60.5   69.5  64.0       1  
4      60.5   69.5  64.0       2

In [32]:
x = coat.drop(['Unnamed: 0','Reviewer_Bought_Size','Review'], axis=1)
y = coat.iloc[:,-1]

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [34]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train , Y_train)
params = {
    'n_estimators':[100],
    'max_depth' : [6, 8, 10, 12], 
    'min_samples_leaf' : [8, 12, 18 ],
    'min_samples_split' : [8, 16, 20]
}
rf_clf = RandomForestClassifier(random_state=0, n_jobs=-1)
grid_cv = GridSearchCV(rf_clf , param_grid=params , cv=2, n_jobs=-1 )
grid_cv.fit(X_train , Y_train)
rf_clf1 = RandomForestClassifier(n_estimators=300, max_depth=10, min_samples_leaf=8, \
                                 min_samples_split=8, random_state=0)
rf_clf1.fit(X_train , Y_train)
pred = rf_clf1.predict(X_test)
print(pred)
print(f'예측 정확도: {accuracy_score(Y_test , pred):.4f}')

[1 1 1 ... 1 1 1]
예측 정확도: 0.8398


In [35]:
joblib.dump(rf_clf1,'./coat_model.pkl', compress=9)

['./coat_model.pkl']